name: ci

on:
  pull_request:
    types: [
        # Default pull_request trigger types.
        opened,
        synchronize,
        reopened,
        # For linting labels. Note that a new job is kicked off per label
        # added or removed.
        labeled,
        unlabeled,
      ]
  push:
    branches: [main]

jobs:
  CheckChanges:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 60 seconds
        run: sleep 60

